name: "Tests - Boutique"
on:
- pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            boutiques
      - name: Where are we and whats around
        run: |
          pwd
          ls
      - run:  |
          cd /
          bosh exec launch /home/runner/work/fnirs-apps-glm-pipeline/fnirs-apps-glm-pipeline/fnirsapp_glm.json /home/runner/work/fnirs-apps-glm-pipeline/fnirs-apps-glm-pipeline/example_invocation.json --debug
        name: Run bosh