
name: "Tests"
on:
- pull_request

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Download test data
        shell: bash -el {0}
        run: |
          curl -L https://github.com/rob-luke/BIDS-NIRS-Tapping/archive/master.zip --output data.zip
          pwd
          unzip data.zip -d ~/example_data
          ls
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker-compose build

      - name: Run docker image
        run: docker-compose up

      - uses: actions/upload-artifact@v1
        with:
          name: Formatted_BIDS_Dataset
          path: /home/runner/example_data/BIDS-NIRS-Tapping-master/derivatives

      - name: Build docker image
        run: docker build --progress=plain -t test .
          
      - name: Run with no arguments
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test

      - name: Run with manual specification of input directory (should find nothing)
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test --input-datasets /bids_dataset2
        
      - name: Run with manual specification of short channels and participants
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test --short-regression False  --subject-label 02 04

      - name: Run with manual specification of participant
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test --subject-label 02
        
      - name: Run with manual specification of exports and subject
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test --subject-label 02 --export-drifts True --export-shorts True
        
      - name: Run with manual specification of
        run: docker run -v /home/runner/example_data/BIDS-NIRS-Tapping-master/:/bids_dataset test --subject-label 02 --output-location /bids_dataset/derivatives/custom
